swipe:
  3:
    left:
      command: "qdbus org.kde.kglobalaccel /component/kwin invokeShortcut 'Switch One Desktop to the Right'"
    right:
      command: "qdbus org.kde.kglobalaccel /component/kwin invokeShortcut 'Switch One Desktop to the Left'"
    up:
      command: "qdbus org.kde.kglobalaccel /component/kwin invokeShortcut 'Switch One Desktop Down'"
    down:
      command: "qdbus org.kde.kglobalaccel /component/kwin invokeShortcut 'Switch One Desktop Up'"
  4:
    left:
      command: "qdbus org.kde.kglobalaccel /component/kwin invokeShortcut 'Window to Next Desktop'"
    right:
      command: "qdbus org.kde.kglobalaccel /component/kwin invokeShortcut 'Window to Previous Desktop'"
    up:
      command: "qdbus org.kde.kglobalaccel /component/kwin invokeShortcut ShowDesktopGrid"
    down:
      command: "qdbus org.kde.kglobalaccel /component/kwin invokeShortcut MinimizeAll"


threshold:
  swipe: 0.5
  # pinch: 1

interval:
  swipe: 0.5
  # pinch: 1
